### ISSUE TITLE
Continues to publish events after cancelling

### ISSUE THREAD

**Issue by contentengineer** [cenkalti/hub#1]
It appears that cancel() does not remove the subscription from the pub/sub; as the hub.subscribers is not updated with result of element removal. Suggest the following:

`if h.id == id {
`
`   h.subscribers[kind] = append(a[:i],a[i+1:]...)
`
`    break
`}

**Comment by cenkalti** [comment]
I didn't understand the bug. The package has a test for ```cancel()```: https://github.com/cenkalti/hub/blob/4bca79c48c6475e4625465739454840ce1ff4f21/hub_test.go#L26

Isn't your case covered by this? Are you using the latest version of this package?

If not can you write a test case to reproduce the problem please?

**Comment by contentengineer** [comment]
Thanks for the quick response. We have been exploring the latest code. You need to extend the cancel test to with  multiple "subscribe" functions to see the problem. Basically it is not updating the h.subscribers[kind] slice after 'cancelling' a subscription.

**Comment by cenkalti** [comment]
@contentengineer Thank you for the bug report and test case. I hope everything is OK now?
